namespace:
  name: sandbox
 
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent
  ports:
  - name: containerPort
    port: 3111
    protocol: TCP
    targetPort: 8080
    nodePort: 30007

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: containerPort

readinessProbe:
   httpGet:
    path: /healthz
    port: containerPort
