namespace:
  name: sandbox
 
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: camhoelscher/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

ports:
  - name: http
    containerPort: 3111

livenessProbe:
  httpGet:
    path: /healthz
    port: http

readinessProbe:
   httpGet:
    path: /healthz
    port: http
